# Generated by Django 5.0.6 on 2025-04-08 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_unit_previous_status_alter_damagepart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('is_fixed', models.BooleanField(default=False)),
                ('previous_status', models.CharField(choices=[('stand_by', 'Stand-by'), ('on_board', 'On Board'), ('under_maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], max_length=20)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='management.unit')),
            ],
        ),
    ]
