# Generated by Django 5.0.6 on 2025-04-09 15:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_damagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default-profile.png', null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='driver_profiles/'),
        ),
    ]
