# Generated by Django 5.0.6 on 2025-04-11 08:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_driver_profile_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='damagepart',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='remittance',
            name='user',
        ),
        migrations.AlterField(
            model_name='damagepart',
            name='part_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_PD',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile1.png', null=True, storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='driver_profiles/'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_PO',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='damagepart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='user',
        ),
    ]
