# Generated by Django 5.0.6 on 2025-04-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_damagepart_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
