# Generated by Django 5.0.6 on 2025-04-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remittanceamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='management.unit'),
        ),
    ]
