# Generated by Django 5.0.6 on 2025-05-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_device_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='gpsdata',
            name='device',
        ),
        migrations.DeleteModel(
            name='Command',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='GPSData',
        ),
    ]
