# Generated by Django 5.0.6 on 2025-05-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_remove_device_unit_remove_gpsdata_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='flespi_device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
