# Generated by Django 5.0.6 on 2025-05-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_unit_flespi_device_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
