# Generated by Django 5.0.6 on 2025-05-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': [models.Case(models.When(status='out_of_service', then=1), default=0, output_field=models.IntegerField()), 'unit_PO']},
        ),
    ]
