# Generated by Django 5.0.6 on 2025-05-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_unit_options_deviceposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='flespi_device_id',
        ),
        migrations.DeleteModel(
            name='DevicePosition',
        ),
    ]
