# Generated by Django 5.0.6 on 2025-05-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_remove_flespi_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='flespi_device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
