# Generated by Django 5.0.6 on 2025-05-08 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_unit_flespi_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='device_imei',
            field=models.CharField(blank=True, help_text='Device IMEI number', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DevicePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='management.unit')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['unit', '-timestamp'], name='management__unit_id_0aa5d8_idx')],
            },
        ),
    ]
