# Generated by Django 5.0.6 on 2025-05-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_unit_device_imei_deviceposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
