# Generated by Django 5.0.6 on 2025-05-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_unit_unit_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='previous_status',
            field=models.CharField(choices=[('stand_by', 'Stand By'), ('in_use', 'In Use'), ('under_maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('stand_by', 'Stand By'), ('in_use', 'In Use'), ('under_maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], default='stand_by', max_length=20),
        ),
    ]
