# Generated by Django 5.0.6 on 2025-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_alter_damagereport_previous_status_alter_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='fixed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
