# Generated by Django 5.0.6 on 2025-05-26 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_damagereport_fixed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
