# Generated by Django 5.0.6 on 2025-05-30 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_remittance_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
